### ISSUE TITLE
AoC legal issue

### ISSUE THREAD

**Issue by felipereyel** [MatheusFarias8/Python-Advent-of-Code-2024#1]
Segundo o Legal do AoC os inputs/respostas/textos não podem ser distribuídos

Veja 
- https://adventofcode.com/2024/about
- https://www.reddit.com/r/adventofcode/comments/1h689qf/2024_day_4_solutions/

**Comment by MatheusFarias8** [comment]
Boa noite, Felipe!

Eu removi os inputs do AoC, conforme: "Se você estiver postando um repositório de código em algum lugar, por favor, não inclua partes do Advento do Código, como o texto do quebra-cabeça ou suas entradas.".

Entretanto, acredito que as minhas repostas podem continuar, observando que eu postei as minhas respostas até o dia 3, e o AoC já se encontra no dia 5, tomei essa decisão baseada no site do AoC que diz: "Posso transmitir minha solução? Por favor, tente evitar dar a solução enquanto as pessoas estão competindo. Se a tabela de classificação diária global de um quebra-cabeça ainda não estiver cheia e você provavelmente ganhará pontos, aguarde para transmitir/postar sua solução até que a tabela de classificação esteja cheia. Se é improvável que você ganhe pontos ou a tabela de classificação diária já está cheia para o quebra-cabeça em que você está trabalhando, o streaming é bom."

Caso eu tenha entendido de maneira errada, sinta-se a vontade de me comunicar para que eu remova tudo.

________________________________
De: Felipe Reyel ***@***.***>
Enviado: quinta-feira, 5 de dezembro de 2024 14:24
Para: MatheusFarias8/Python-Advent-of-Code-2024 ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: [MatheusFarias8/Python-Advent-of-Code-2024] AoC legal issue (Issue #1)


Segundo o Legal do AoC os inputs/respostas/textos não podem ser distribuídos

Veja

  *   https://adventofcode.com/2024/about
  *   https://www.reddit.com/r/adventofcode/comments/1h689qf/2024_day_4_solutions/
